name: pf

services:
  db:
    profiles:
      - dev
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: perfi_dev
      POSTGRES_DB: perfi
      POSTGRES_PASSWORD: perfi_dev_pass
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db

  test_db:
    profiles:
      - test
      - dev
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: perfi_test
      POSTGRES_DB: perfi_test
      POSTGRES_PASSWORD: perfi_test_pass
    tmpfs:
      - /var/lib/postgresql/data
    container_name: test_db

volumes:
  postgres_data:
