"""Make transaction category nullable.

Revision ID: 7249dfc19dd1
Revises: 15ac639408bc
Create Date: 2025-03-15 12:42:59.896946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7249dfc19dd1"
down_revision: Union[str, None] = "15ac639408bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "category_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
