"""Make transaction.category_id non-nullable.

Revision ID: 96906aa1b643
Revises: 5865eeb9f7e3
Create Date: 2025-03-16 15:54:57.531234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96906aa1b643"
down_revision: Union[str, None] = "5865eeb9f7e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "category_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
