"""Associate categories with users.

Revision ID: 15ac639408bc
Revises: 8adbdb54a4df
Create Date: 2025-03-15 12:28:56.430439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15ac639408bc"
down_revision: Union[str, None] = "8adbdb54a4df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_category_user_id",
        "category",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("category", "color")
    op.drop_column("category", "icon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category",
        sa.Column("icon", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    )
    op.add_column(
        "category",
        sa.Column("color", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_category_user_id", "category", type_="foreignkey")
    op.drop_column("category", "user_id")
    # ### end Alembic commands ###
