"""Initial.

Revision ID: 5d10ad89314d
Revises:
Create Date: 2025-03-15 13:28:34.380230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d10ad89314d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("hashed_password", sa.LargeBinary(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_updated_at"), "user", ["updated_at"], unique=False)
    op.create_table(
        "account",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "CHECKING",
                "SAVINGS",
                "INVESTMENT",
                "CREDIT",
                "CASH",
                name="accounttype",
            ),
            nullable=False,
        ),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("institution", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_account_updated_at"), "account", ["updated_at"], unique=False
    )
    op.create_table(
        "category",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "category_type",
            sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="categorytype"),
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_category_updated_at"),
        "category",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "refresh_token",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_value", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_refresh_token_token_value"),
        "refresh_token",
        ["token_value"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_token_updated_at"),
        "refresh_token",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "transaction",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_pending", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["category.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_transaction_account_id"),
        "transaction",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_category_id"),
        "transaction",
        ["category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_transaction_date"), "transaction", ["date"], unique=False)
    op.create_index(
        op.f("ix_transaction_updated_at"),
        "transaction",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_updated_at"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_date"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_category_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_account_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_refresh_token_updated_at"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_token_value"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_category_updated_at"), table_name="category")
    op.drop_table("category")
    sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="categorytype").drop(op.get_bind())
    op.drop_index(op.f("ix_account_updated_at"), table_name="account")
    op.drop_table("account")
    sa.Enum(
        "CHECKING",
        "SAVINGS",
        "INVESTMENT",
        "CREDIT",
        "CASH",
        name="accounttype",
    ).drop(op.get_bind())
    op.drop_index(op.f("ix_user_updated_at"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
