"""Remove username from User model.

Revision ID: f31a63b4d18f
Revises: 96906aa1b643
Create Date: 2025-03-29 21:27:53.018329

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f31a63b4d18f"
down_revision: str | None = "96906aa1b643"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
