version: 1
disable_existing_loggers: False


formatters:
  basic:
    format: '[%(asctime)s] - %(name)s - %(levelname)s - %(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  colored:
    (): config.logging.ColoredFormatter


handlers:
  basic:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout
  app_log:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout


filters:
  disable_log:
    (): config.logging.DisableLogFilter


loggers:
  perfi:
    level: DEBUG
    handlers: [app_log]
    propagate: no

  sqlalchemy:
    level: WARNING
    handlers: [app_log]
    propagate: no

  werkzeug:
    level: ERROR
    handlers: []
    propagate: no

  alembic:
    level: DEBUG
    handlers: [app_log]
    propagate: no

  migrations:
    level: DEBUG
    handlers: [basic]
    propagate: no

  uvicorn.access:
    handlers: []
    propagate: no
    level: WARNING
    filters: [disable_log]

root:
  level: WARNING
  handlers: [basic]
