"""empty message

Revision ID: 648f0af4b146
Revises:
Create Date: 2024-12-07 16:38:51.232174

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "648f0af4b146"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # commented these out because I ran `flask dbx drop && flask dbx create` instead.
    # with op.batch_alter_table('accounts', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False))

    # with op.batch_alter_table('transactions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False))

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False))
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("_updated_at")

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("_updated_at")

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("_updated_at")

    # ### end Alembic commands ###
