"""empty message

Revision ID: ac79b6c59474
Revises: 7bf73bd273e3
Create Date: 2024-12-25 15:54:50.032809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac79b6c59474"
down_revision = "7bf73bd273e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('transactions_file_import') <- Note: did this manually
    op.create_table(
        "transactions_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "_status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="transactionsfileimportstatus",
            ),
            nullable=False,
        ),
        sa.Column("preview_data", sa.JSON(), nullable=True),
        sa.Column("mapped_headers", sa.JSON(), nullable=True),
        sa.Column("error_log", sa.JSON(), nullable=True),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename", "user_id", name="uq_filename_user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions_file_import",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "file_path", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "error_log",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "processed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("retry_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "_created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "_status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="transactionsfileimportstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="transactions_file_import_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="transactions_file_import_pkey"),
        sa.UniqueConstraint("filename", "user_id", name="uq_filename_user"),
    )
    op.drop_table("transactions_files")
    # ### end Alembic commands ###
