"""empty message

Revision ID: bff8f25b91f1
Revises: fc7a9aac30eb
Create Date: 2024-12-27 15:57:31.604645

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bff8f25b91f1"
down_revision = "fc7a9aac30eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, "transactions_files", ["file_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("file_id")

    # ### end Alembic commands ###
